[project]
name = "time_optimal_trajectory_generation"
version = "0.1.0"
description = "Add a short description here"
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
configure = "cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . .build/relwithdebinfo"
build = { cmd = "cmake --build .build/relwithdebinfo", depends-on = [
  "configure",
] }
install = { cmd = "cmake --install .build/relwithdebinfo --prefix .pixi/envs/default", depends-on = [
  "build",
] }
conda-build = "rattler-build build --output-dir .build/conda --recipe rattler-recipe/recipe.yaml"
upload = "rattler-build upload prefix --channel testing "

[feature.wheel.tasks]

build-wheels = { cmd = [
  "cibuildwheel",
  ".",
  "--platform",
  "linux",
], cwd = ".", env = { CIBW_BUILD = "cp3{10,11,12}-macosx_{x86_64,arm64} cp3{9,10,11,12}-manylinux_x86_64", CIBW_BUILD_VERBOSITY = "1" } }


[feature.wheel.dependencies]
cibuildwheel = ">=2.21.3,<3"

[dependencies]
ninja = ">=1.12.1,<1.13"
cmake = ">=3.29.3,<3.30"
lld = ">=18.1.5,<18.2"
eigen = ">=3.4.0,<3.5"
python = "==3.11"
numpy = ">=1.26.4,<1.27"
rattler-build = ">=0.16.2,<0.17"

[environments]
wheel = { features = ["wheel"], no-default-feature = true }
