[project]
name        = "time_optimal_trajectory_generation"
version     = "0.1.0"
description = "Add a short description here"
authors     = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels    = ["conda-forge"]
platforms   = ["linux-64"]

[tasks]
configure = "cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . build/relwithdebinfo"
build     = { cmd = "cmake --build build/relwithdebinfo", depends-on = ["configure"] }
install   = { cmd = "cmake --install build/relwithdebinfo --prefix $CONDA_PREFIX", depends-on = ["build"] }

[dependencies]
ninja  = ">=1.12.1,<1.13"
cmake  = ">=3.29.3,<3.30"
lld    = ">=18.1.5,<18.2"
python = ">=3.11,<3.12"
numpy = ">=1.26.4,<1.27"

[pypi-dependencies]
time_optimal_trajectory_generation_py = { path = ".", editable = true }
