context:
  version: "0.0.1"

package:
  name: time_optimal_trajectory_generation_py
  version: ${{ version }}

source:
  git: https://github.com/JafarAbdi/time_optimal_trajectory_generation_py.git

build:
  number: 0
  script: |
    cmake ${CMAKE_ARGS} -GNinja \
          -DCMAKE_INSTALL_PREFIX=$PREFIX \
          -DCMAKE_BUILD_TYPE=Release \
          $SRC_DIR
    ninja install

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - pybind11
    - eigen
    - python==3.11
    - libxcrypt # TODO: Why do we need this?
  host:
    - python==3.11
