name: Build package

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build conda package
      uses: prefix-dev/rattler-build-action@v0.2.15
      with:
        recipe-path: rattler-recipe/recipe.yaml
    - run: |
        for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
          echo "Uploading ${pkg}"
          rattler-build upload prefix -c ramp "${pkg}"
        done
      env:
        PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}
